<a href="https://colab.research.google.com/github/RichardLDM/AI-foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("Student_performance_data _.csv")

print("Dataset shape (rows, columns):", df.shape)
print("Column name:", df.columns.tolist())

print(df.head())

print("Summary statistics:")
print(df.describe())

print("Data types and null info:")
print(df.info())

Dataset shape (rows, columns): (2392, 15)
Column name: ['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation', 'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA', 'GradeClass']
   StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          0                  2        19.833723
1       1002   18       0          0                  1        15.408756
2       1003   15       0          2                  3         4.210570
3       1004   17       1          0                  3        10.028829
4       1005   17       1          0                  2         4.672495

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0         7         1                2                0       0      1
1         0         0                1                0       0      0
2        26         0                2                0       0      0
3        14         0                3                1       0      0
4        17         1                3                0       0      0

   Volunteering       GPA  GradeClass
0             0  2.929196         2.0
1             0  3.042915         1.0
2             0  0.112602         4.0
3             0  2.054218         3.0
4             0  1.288061         4.0
Summary statistics:
         StudentID          Age       Gender    Ethnicity  ParentalEducation  \
count  2392.000000  2392.000000  2392.000000  2392.000000        2392.000000
mean   2196.500000    16.468645     0.510870     0.877508           1.746237
std     690.655244     1.123798     0.499986     1.028476           1.000411
min    1001.000000    15.000000     0.000000     0.000000           0.000000
25%    1598.750000    15.000000     0.000000     0.000000           1.000000
50%    2196.500000    16.000000     1.000000     0.000000           2.000000
75%    2794.250000    17.000000     1.000000     2.000000           2.000000
max    3392.000000    18.000000     1.000000     3.000000           4.000000

       StudyTimeWeekly     Absences     Tutoring  ParentalSupport  \
count      2392.000000  2392.000000  2392.000000      2392.000000
mean          9.771992    14.541388     0.301421         2.122074
std           5.652774     8.467417     0.458971         1.122813
min           0.001057     0.000000     0.000000         0.000000
25%           5.043079     7.000000     0.000000         1.000000
50%           9.705363    15.000000     0.000000         2.000000
75%          14.408410    22.000000     1.000000         3.000000
max          19.978094    29.000000     1.000000         4.000000

       Extracurricular       Sports        Music  Volunteering          GPA  \
count      2392.000000  2392.000000  2392.000000   2392.000000  2392.000000
mean          0.383361     0.303512     0.196906      0.157191     1.906186
std           0.486307     0.459870     0.397744      0.364057     0.915156
min           0.000000     0.000000     0.000000      0.000000     0.000000
25%           0.000000     0.000000     0.000000      0.000000     1.174803
50%           0.000000     0.000000     0.000000      0.000000     1.893393
75%           1.000000     1.000000     0.000000      0.000000     2.622216
max           1.000000     1.000000     1.000000      1.000000     4.000000

        GradeClass
count  2392.000000
mean      2.983696
std       1.233908
min       0.000000
25%       2.000000
50%       4.000000
75%       4.000000
max       4.000000
Data types and null info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB
None

In [21]:
print("Average score by columns:")
df[["GPA", "Volunteering"]].mean()

Average score by columns:

GPA             1.906186
Volunteering    0.157191
dtype: float64

In [20]:
print("MAX score by columns:")
df[["GPA", "Volunteering"]].max()

MAX score by columns:

GPA             4.0
Volunteering    1.0
dtype: float64

In [23]:
print("MAX score by columns:")
df[["GPA", "Volunteering"]].min()

MAX score by columns:

GPA             0.0
Volunteering    0.0
dtype: float64

In [24]:
# Correlation
print("Correlation")
df[["GPA", "Volunteering"]].corr()

Correlation

                   GPA  Volunteering
GPA           1.000000      0.003258
Volunteering  0.003258      1.000000

In [32]:
df["Total score"] = df[["GPA", "GradeClass"]].sum(axis=1)
df["average score"] = df["Total score"] / 2
df["passed"] = np.where(df["average score"] >= 2, "Pass", "Fail")

print("New columns preview(total, avergae, passed):")
print(df[["Total score", "average score", "passed"]])

New columns preview(total, avergae, passed):
      Total score  average score passed
0        4.929196       2.464598   Pass
1        4.042915       2.021457   Pass
2        4.112602       2.056301   Pass
3        5.054218       2.527109   Pass
4        5.288061       2.644031   Pass
...           ...            ...    ...
2387     3.455509       1.727755   Fail
2388     7.279150       3.639575   Pass
2389     3.142333       1.571166   Fail
2390     2.803297       1.401648   Fail
2391     3.140014       1.570007   Fail

[2392 rows x 3 columns]

In [41]:
test_prep_group = df.groupby("Tutoring") [["GPA", "GradeClass"]].mean()
print("Grouped by Tutoring")
print(test_prep_group)

# Gender

gender_avg = df.groupby("Gender") [["GPA", "GradeClass"]].mean()
print("Grouped by gender")
print(gender_avg)

# Who passed vs failed
pass_rate = df["passed"].value_counts(normalize=True) * 100
print("Passed vs failed")
print(pass_rate)

Grouped by Tutoring
               GPA  GradeClass
Tutoring
0         1.818968    3.074207
1         2.108325    2.773925
Grouped by gender
             GPA  GradeClass
Gender
0       1.918679    2.954701
1       1.894225    3.011457
Passed vs failed
passed
Pass    93.060201
Fail     6.939799
Name: proportion, dtype: float64

In [44]:
# Convert scores to Numpy array
scores = df[["GPA", "GradeClass"]].values

# Mean, Std Deviation
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std Deviation:", np.std(scores, axis=0))

# Z-score (normalize)
z_scores = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-score:")
print(z_scores[:5])

Numpy Mean: [1.9061863  2.98369565]
Numpy Std Deviation: [0.91496451 1.23364961]
Z-score:
[[ 1.11808631 -0.79738659]
 [ 1.24237446 -1.60798953]
 [-1.96027719  0.82381929]
 [ 0.1617897   0.01321635]
 [-0.67557279  0.82381929]]

In [52]:
# How many students scored above 3 avaerge?
top_scorers = df[df["average score"] >= 2.5]
print("Number of students with an average score of 3 or higher:", len(top_scorers))

# How many failed
failed_students = df[df["passed"] == "Fail"]
print("Number of students who failed:", len(failed_students))

Number of students with an average score of 3 or higher: 1165
Number of students who failed: 166